# Generated by Django 4.1.3 on 2023-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default='NEW', max_length=15, null=True),
        ),
    ]
